# Generated by Django 5.1.15 on 2026-06-30 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('landing_path', models.CharField(blank=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('started', 'Iniciado')], default='started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_events', to='analytics.visitorsession')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_clicks', to='analytics.visitorsession')),
            ],
        ),
        migrations.CreateModel(
            name='ProductViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='catalog.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='analytics.visitorsession')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='analytics_p_created_a24768_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('page_label', models.CharField(blank=True, max_length=60)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_duration_final', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='analytics.visitorsession')),
            ],
            options={
                'indexes': [models.Index(fields=['entered_at'], name='analytics_p_entered_1f873a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('add', 'Agregar'), ('remove', 'Quitar'), ('update', 'Actualizar')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_events', to='analytics.visitorsession')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='analytics_c_created_838a60_idx')],
            },
        ),
        migrations.CreateModel(
            name='WishlistEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('add', 'Agregar'), ('remove', 'Quitar')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_events', to='analytics.visitorsession')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='analytics_w_created_7872bd_idx')],
            },
        ),
    ]
