# Generated by Django 5.1.15 on 2026-07-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='combo_products',
            field=models.ManyToManyField(blank=True, help_text='Productos que incluye este combo (solo aplica si es_combo está activo).', related_name='included_in_combos', to='catalog.product'),
        ),
    ]
