# Generated by Django 5.1.15 on 2026-06-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemextra',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
