# Generated by Django 5.1.15 on 2026-07-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_access_token_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'WhatsApp',
                'verbose_name_plural': 'WhatsApp (conectar número)',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
