# Generated by Django 5.1.15 on 2026-07-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_seed_delivery_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualsale',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], default='whatsapp', max_length=10),
        ),
    ]
